"""empty message

Revision ID: 229c3f4d17d1
Revises: d6c1ed6ff8b4
Create Date: 2020-04-25 15:45:13.307592

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '229c3f4d17d1'
down_revision = 'd6c1ed6ff8b4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('todo', sa.Column('user_name', sa.String(length=80), nullable=False))
    op.drop_index('done', table_name='todo')
    op.drop_index('label', table_name='todo')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('label', 'todo', ['label'], unique=True)
    op.create_index('done', 'todo', ['done'], unique=True)
    op.drop_column('todo', 'user_name')
    # ### end Alembic commands ###
